"""SQLAlchemy models for the knowledge point candidate system.

Includes KnowledgePointCandidate, KnowledgePointAlias, KnowledgePointMergeLog,
and QuestionKnowledgeCandidate.

These models support the P0 pipeline refactoring: LLM-discovered knowledge concepts
that are not yet in the official knowledge point tree can be stored as candidates
pending human review.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class KnowledgePointCandidate(Base):
    """A proposed knowledge point candidate, typically generated by an LLM or human reviewer."""

    __tablename__ = "knowledge_point_candidates"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    candidate_id: Mapped[str] = mapped_column(
        String(50), unique=True, nullable=False, index=True
    )
    canonical_name: Mapped[str] = mapped_column(String(200), nullable=False)
    definition: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    suggested_parent_path: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True
    )
    suggested_parent_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("knowledge_points.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    confidence: Mapped[float] = mapped_column(Float, default=0.5, nullable=False)
    source: Mapped[str] = mapped_column(
        String(20), default="llm", nullable=False
    )  # human, llm, import, merged
    status: Mapped[str] = mapped_column(
        String(20), default="pending", nullable=False, index=True
    )  # pending, approved, rejected, merged
    source_question_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("questions.id", ondelete="SET NULL"), nullable=True, index=True
    )
    source_document_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("source_documents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    source_text_snippet: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    reviewer: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    review_note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    merged_into_kp_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("knowledge_points.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Relationships
    source_question: Mapped[Optional["Question"]] = relationship(
        "Question", foreign_keys=[source_question_id], overlaps="spawned_kp_candidates"
    )
    source_document: Mapped[Optional["SourceDocument"]] = relationship("SourceDocument")
    suggested_parent: Mapped[Optional["KnowledgePoint"]] = relationship(
        "KnowledgePoint", foreign_keys=[suggested_parent_id]
    )
    merged_into: Mapped[Optional["KnowledgePoint"]] = relationship(
        "KnowledgePoint", foreign_keys=[merged_into_kp_id]
    )
    question_links: Mapped[list["QuestionKnowledgeCandidate"]] = relationship(
        "QuestionKnowledgeCandidate",
        back_populates="knowledge_point_candidate",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return (
            f"<KnowledgePointCandidate(id={self.id}, candidate_id={self.candidate_id!r}, "
            f"name={self.canonical_name!r}, status={self.status!r})>"
        )


class KnowledgePointAlias(Base):
    """An alternative name (alias) for an existing knowledge point."""

    __tablename__ = "knowledge_point_aliases"
    __table_args__ = (
        UniqueConstraint("knowledge_point_id", "alias", name="uq_kp_alias"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    knowledge_point_id: Mapped[int] = mapped_column(
        ForeignKey("knowledge_points.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    alias: Mapped[str] = mapped_column(String(300), nullable=False)
    language: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    # language: zh, en, etc.
    source: Mapped[str] = mapped_column(
        String(20), default="llm", nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )

    # Relationship
    knowledge_point: Mapped["KnowledgePoint"] = relationship(
        "KnowledgePoint", back_populates="aliases"
    )

    def __repr__(self) -> str:
        return (
            f"<KnowledgePointAlias(id={self.id}, kp_id={self.knowledge_point_id}, "
            f"alias={self.alias!r})>"
        )


class KnowledgePointMergeLog(Base):
    """A log entry recording a knowledge point merge operation."""

    __tablename__ = "knowledge_point_merge_logs"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    merged_from_id: Mapped[int] = mapped_column(
        ForeignKey("knowledge_points.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    merged_to_id: Mapped[int] = mapped_column(
        ForeignKey("knowledge_points.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    reviewer: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    merged_from: Mapped["KnowledgePoint"] = relationship(
        "KnowledgePoint",
        foreign_keys=[merged_from_id],
        back_populates="merge_logs_from",
    )
    merged_to: Mapped["KnowledgePoint"] = relationship(
        "KnowledgePoint",
        foreign_keys=[merged_to_id],
        back_populates="merge_logs_to",
    )

    def __repr__(self) -> str:
        return (
            f"<KnowledgePointMergeLog(id={self.id}, "
            f"from={self.merged_from_id}, to={self.merged_to_id})>"
        )


class QuestionKnowledgeCandidate(Base):
    """Association between a question and a knowledge point candidate.
    Mirrors QuestionKnowledgePoint but for candidates instead of approved KPs.
    """

    __tablename__ = "question_knowledge_candidates"
    __table_args__ = (
        UniqueConstraint(
            "question_id", "knowledge_point_candidate_id", name="uq_q_kpc"
        ),
    )

    question_id: Mapped[int] = mapped_column(
        ForeignKey("questions.id", ondelete="CASCADE"), primary_key=True
    )
    knowledge_point_candidate_id: Mapped[int] = mapped_column(
        ForeignKey("knowledge_point_candidates.id", ondelete="CASCADE"),
        primary_key=True,
    )
    weight: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)
    is_primary: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Relationships
    question: Mapped["Question"] = relationship(
        "Question", back_populates="knowledge_point_candidates"
    )
    knowledge_point_candidate: Mapped["KnowledgePointCandidate"] = relationship(
        "KnowledgePointCandidate", back_populates="question_links"
    )

    def __repr__(self) -> str:
        return (
            f"<QuestionKnowledgeCandidate(question_id={self.question_id}, "
            f"candidate_id={self.knowledge_point_candidate_id})>"
        )
